#!/usr/bin/env ts-node

/**
 * Script to generate SQL migration for seeding program templates
 * Reads programs from app/lib/programs.ts and generates SQL INSERT statements
 */

import { allPrograms } from '../app/lib/programs';

function escapeSQL(str: string | undefined): string {
  if (!str) return 'NULL';
  return `'${str.replace(/'/g, "''")}'`;
}

function generateProgramSeedSQL(): string {
  let sql = `-- Seed all built-in program templates
-- Generated by scripts/generate-program-seed.ts

DO $$
DECLARE
`;

  // Declare UUID variables for each program
  allPrograms.forEach(program => {
    sql += `  ${program.id.replace(/-/g, '_')}_template_id UUID;\n`;
  });

  sql += `BEGIN\n\n`;

  // Insert each program
  allPrograms.forEach((program, programIndex) => {
    const programVarName = program.id.replace(/-/g, '_');

    sql += `  -- ================================================\n`;
    sql += `  -- Program ${programIndex + 1}/${allPrograms.length}: ${program.name}\n`;
    sql += `  -- ================================================\n\n`;

    // Insert program_template
    sql += `  -- Insert program template\n`;
    sql += `  INSERT INTO program_templates (\n`;
    sql += `    name,\n`;
    sql += `    description,\n`;
    sql += `    goal,\n`;
    sql += `    difficulty,\n`;
    sql += `    duration_weeks,\n`;
    sql += `    days_per_week,\n`;
    sql += `    periodization_type,\n`;
    sql += `    is_system,\n`;
    sql += `    app_metadata\n`;
    sql += `  ) VALUES (\n`;
    sql += `    ${escapeSQL(program.name)},\n`;
    sql += `    ${escapeSQL(program.description)},\n`;
    sql += `    ${escapeSQL(program.goal || 'general')},\n`;
    sql += `    ${escapeSQL(program.experienceLevel || 'intermediate')},\n`;
    sql += `    ${program.weekCount || program.weeks.length},\n`;
    sql += `    ${program.daysPerWeek || 4},\n`;
    sql += `    ${escapeSQL(program.intensityMethod || 'rpe')},\n`;
    sql += `    true,\n`;
    sql += `    jsonb_build_object('app_program_id', ${escapeSQL(program.id)})\n`;
    sql += `  ) RETURNING id INTO ${programVarName}_template_id;\n\n`;

    // Insert weeks, days, and sets
    program.weeks.forEach((week, weekIndex) => {
      const weekVarName = `${programVarName}_week${weekIndex + 1}_id`;
      sql += `  -- Week ${week.weekNumber}\n`;
      sql += `  INSERT INTO program_weeks (program_id, week_number) VALUES\n`;
      sql += `    (${programVarName}_template_id, ${week.weekNumber})\n`;
      sql += `  RETURNING id INTO ${weekVarName};\n\n`;

      week.days.forEach((day, dayIndex) => {
        const dayVarName = `${programVarName}_w${weekIndex + 1}_day${dayIndex}_id`;
        sql += `  -- Week ${week.weekNumber}, Day ${dayIndex + 1}: ${day.name}\n`;
        sql += `  INSERT INTO program_days (week_id, day_index, day_of_week, name, focus) VALUES\n`;
        sql += `    (${weekVarName}, ${dayIndex}, ${escapeSQL(day.dayOfWeek)}, ${escapeSQL(day.name)}, ${escapeSQL(day.name)})\n`;
        sql += `  RETURNING id INTO ${dayVarName};\n\n`;

        if (day.sets.length > 0) {
          sql += `  -- Sets for ${day.name}\n`;
          sql += `  INSERT INTO program_sets (\n`;
          sql += `    day_id,\n`;
          sql += `    exercise_id,\n`;
          sql += `    order_index,\n`;
          sql += `    set_index,\n`;
          sql += `    prescribed_reps,\n`;
          sql += `    target_rpe,\n`;
          sql += `    target_rir,\n`;
          sql += `    rest_seconds,\n`;
          sql += `    notes\n`;
          sql += `  ) VALUES\n`;

          day.sets.forEach((set, setIdx) => {
            sql += `    (\n`;
            sql += `      ${dayVarName},\n`;
            sql += `      (SELECT id FROM exercises WHERE slug = ${escapeSQL(set.exerciseId)}),\n`;
            sql += `      ${setIdx},\n`;
            sql += `      ${set.setIndex},\n`;
            sql += `      ${escapeSQL(set.prescribedReps)},\n`;
            sql += `      ${set.targetRPE || 'NULL'},\n`;
            sql += `      ${set.targetRIR || 'NULL'},\n`;
            sql += `      ${set.restSeconds || 'NULL'},\n`;
            sql += `      ${escapeSQL(set.notes)}\n`;
            sql += `    )${setIdx < day.sets.length - 1 ? ',' : ';'}\n`;
          });
          sql += `\n`;
        }
      });
    });

    sql += `\n`;
  });

  sql += `END $$;\n`;

  return sql;
}

// Generate and output SQL
const sql = generateProgramSeedSQL();
console.log(sql);

// Also save to file
const fs = require('fs');
const path = require('path');
const outputPath = path.join(__dirname, '../supabase/migrations/007_seed_program_templates.sql');
fs.writeFileSync(outputPath, sql);
console.error(`\n✅ SQL migration generated at: ${outputPath}`);
